[[Activities__createRecurringActivity]]
==== Activities : Create Recurring Activity

Create a new <<RecurringActivity, Recurring Activity>> after entering an activity name and start date and start time and a periodicity (weekly, monthly etc). Child <<ActivityEvent, Activities>> can then be scheduled into the future from this 'parent'.

[[Activities__listAllRecurringActivities]]
==== Activities : List All Recurring Activities

List all <<RecurringActivity, Recurring Activities>> (should we filter these??)

[[Activities__findRecurringActivityByName]]
==== Activities : Find Recurring Activity By Name

List all <<RecurringActivity, Recurring Activities>> with a name starting with an entered value.

[[Activities__createOneOffActivity]]
==== Activities : Create One Off Activity

Create a new <<ActivityEvent, One-off Activity>> after entering an activity name and start date and start time value. 

[[Activities__findActivityByName]]
==== Activities : Find Activity By Name

Search for all <<ActivityEvent, Activities>> having a specific name.

[[Activities__listAllFutureActivities]]
==== Activities : List All Future Activities

Get a list of <<ActivityEvent, Activities>> having a start date-time in the future.

[[Activities__listAllPastActivities]]
==== Activities : List All Past Activitie

Get a list of <<ActivityEvent, Activities>> having a start date-time in the past. [Note: maybe a List all Archived Activities option will be added too].
